site_name: LlamaDB
site_description: High-performance vector database optimized for AI workloads with MLX acceleration for Apple Silicon
site_Author: Nik Jois
site_url: https://github.com/llamasearch-ai/llamadb

repo_name: llamasearch-ai/llamadb
repo_url: https://github.com/llamasearch-ai/llamadb
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_source: true
            show_root_heading: true
            show_category_heading: true
            heading_level: 3

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Installation: installation.md
  - User Guide:
    - Getting Started: user-guide/getting-started.md
    - Core Concepts: user-guide/core-concepts.md
    - Vector Indexes: user-guide/vector-indexes.md
    - MLX Acceleration: user-guide/mlx-acceleration.md
    - Filtering: user-guide/filtering.md
    - Rest API: user-guide/rest-api.md
  - API Reference:
    - Core: api/core.md
    - Vector Index: api/vector-index.md
    - Database: api/database.md
    - Utilities: api/utilities.md
    - REST API: api/rest.md
  - Examples:
    - Basic Usage: examples/basic-usage.md
    - Similarity Search: examples/similarity-search.md
    - Metadata Filtering: examples/metadata-filtering.md
    - MLX Acceleration: examples/mlx-acceleration.md
    - API Server: examples/api-server.md
  - Development:
    - Contributing: development/contributing.md
    - Architecture: development/architecture.md
    - Rust Extensions: development/rust-extensions.md
    - Testing: development/testing.md
    - Benchmarking: development/benchmarking.md
  - Roadmap: roadmap.md
  - Changelog: changelog.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/llamasearch-ai
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/llamasearch
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/llamadb/

copyright: Copyright &copy; 2023 - 2024 LlamaSearch.AI Team 