apiVersion: v1
kind: ConfigMap
metadata:
  name: llamadb-config
  labels:
    app: llamadb
data:
  LLAMADB_ENV: "production"
  LLAMADB_LOG_LEVEL: "INFO"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llamadb
  labels:
    app: llamadb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: llamadb
  template:
    metadata:
      labels:
        app: llamadb
    spec:
      containers:
      - name: llamadb
        image: llamadb:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
        envFrom:
        - configMapRef:
            name: llamadb-config
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "2"
            memory: "2Gi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 15
        volumeMounts:
        - name: data
          mountPath: /app/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: llamadb-data
---
apiVersion: v1
kind: Service
metadata:
  name: llamadb
  labels:
    app: llamadb
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: llamadb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llamadb-data
  labels:
    app: llamadb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: llamadb
  labels:
    app: llamadb
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: llamadb.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: llamadb
            port:
              number: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: llamadb
  labels:
    app: llamadb
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: llamadb
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80 