version: '3'

services:
  rag-example:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    ports:
      - "8000:8000"  # Only needed if we add a web interface
    deploy:
      resources:
        limits:
          memory: 4G 